
sharding:
  jdbc:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
#        jdbc-url: jdbc:mysql://10.250.250.116:3306/ds0?useUnicode=true&characterEncoding=utf8&useSSL=false
        jdbc-url: jdbc:mysql://10.250.250.216:3306/ds0?useUnicode=true&characterEncoding=utf8&useSSL=false
#        username: root
        username: fsccc
#        password: root
        password: 123456

      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://10.250.250.216:3306/ds1?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: fsccc
        password: 123456

    config:
      sharding:
        default-database-strategy:
          standard:
            precise-algorithm-class-name: shardingsphere.demo.strategy.HashCodePreciseShardingAlgorithm
            sharding-column: order_id
        tables:
          t_order:
            actual-data-nodes: ds$->{0..1}.t_order_$->{0..1}
            table-strategy:
              standard:
                precise-algorithm-class-name: shardingsphere.demo.strategy.HashCodePreciseShardingAlgorithm
                sharding-column: user_id
            key-generator-column-name: id
